### ISSUE TITLE
Fix e2e setup script

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-substrate-pallets#103]
After the update to Polkadot v0.9.42 the e2e setup script is using wrong types and also doesn't register the MPC address.

**Comment by freddyli7** [comment]
@mpetrun5 as I remember we decided to put mpc address in the env var

**Comment by freddyli7** [comment]
ok then, do you have any preference on mpc address? or just keep it in the env var?

**Comment by mpetrun5** [comment]
Whoever has access to the actions environment variables in settings has to set to whatever it was before for the e2e tests
