### ISSUE TITLE
sygmabridge_issues

### ISSUE THREAD

**Issue by firebeegit** [sygmaprotocol/sygma-substrate-pallets#129]
![image](https://github.com/sygmaprotocol/sygma-substrate-pallets/assets/141648418/f31dc3c3-8568-4e56-bb2f-12b71b427c1c)

and

![image](https://github.com/sygmaprotocol/sygma-substrate-pallets/assets/141648418/876da854-92ae-4e3b-872d-437cf87bb3c0)

Hi Team,
we are trying to add sygmabridge in my polkadot relaychain code . everything to be added and installed except runtime lib.rs file inside the construct_runtime function . let me know any solution . I attached screenshot to this message.

Thank you,

**Comment by freddyli7** [comment]
hey @firebeegit, from the screenshots you attached I'm not able to identify what kind issue you were facing, can you please provide more context?

**Comment by freddyli7** [comment]
@firebeegit please reach out to us on our discord if you have any further questions, I will close this issue for now.
