### ISSUE TITLE
Question about Standalone Impl.

### ISSUE THREAD

**Issue by alfellati** [sygmaprotocol/sygma-substrate-pallets#152]
I'm building a standalone node called [Setheum](https://github.com/Setheum-Labs/Setheum) and it doesn't use GRANDPA for finality, it rather uses [AlephBFT](https://github.com/Cardinal-Cryptography/AlephBFT) for finality and AURA for block production. Will this [standalone implementation] work with other than GRANDPA Engine? Thanks a lot in advance.

**Comment by tolak** [comment]
@alfellati If you integrate it into substrate blockchain, these pallets are only part of runtime, consensus will not affect the functionalities

**Comment by alfellati** [comment]
Thanks @tolak. Do we have to run our own relayer nodes or how do we partner up to get our network added?

**Comment by alexmmueller** [comment]
Hey @alfellati! Can you please join the [Sygma Discord](https://discord.com/invite/Qdf6GyNB5J)? We can help you there to get your network added.
