### ISSUE TITLE
Implement PHA <> ERC20 decimal conversions function

### ISSUE THREAD

**Issue by P1sar** [sygmaprotocol/sygma-substrate-pallets#51]
**Abstract**
PHA token has 12 (?) decimals and most of the ERC20 tokens have 18 decimals. To make them compatible we should implement a rounding function inside the pallet. (we will also implement one just in case for solidity).  Generally, we decided that the sygma protocol will operate with 18 decimals by default. So all the onchain entities should expect every incoming message to have 18 decimals and should by itself convert it to required. The same is for outgoing messages, onchain entities should convert from local decimals to protocol 18 decimals. 
**Implementation details** 
The pallet should always expect 18 decimals from Relayer when it calls ExecuteProposal, and Relayer is always expecting the Pallet to event deposit with an amount rounded for 18 decimals. For this implement a Rounding function that converts from local to protocol decimals on deposit Event and execution
**local_decimal** param should be a part of pallets runtime configuration.  And should be one-to-one for each token! 

**Acceptance criteria**:
Unit tests

**Comment by freddyli7** [comment]
Add a `DecimalConverter` Trait and impl it in the substrate-node runtime, there will be no on-chain storage to store the asset and its decimal mappings, instead, those info will be configured in the runtime config and trait will provide the methods to do the actual conversion
