### ISSUE TITLE
Upgrade polkadot/substrate to 0.9.37

### ISSUE THREAD

**Issue by tolak** [sygmaprotocol/sygma-substrate-pallets#59]
Since the v0.9.33 that we currently use is too old, it's time to upgrade it to 0.9.37

- Upgrade Substrate to branch `polkadot-v0.9.37`
- Upgrade Polkadot to branch `release-v0.9.37`
- Pallet changes adaption

**Comment by freddyli7** [comment]
@tolak this issue has been merged right ? https://github.com/sygmaprotocol/sygma-substrate-pallets/pull/61

**Comment by tolak** [comment]
@freddyli7 Yes, let me close this issue
