### ISSUE TITLE
Implement DynamicFeeHandler for EVM as a target network

### ISSUE THREAD

**Issue by P1sar** [sygmaprotocol/sygma-substrate-pallets#60]
When Substrate -> EVM deposit is happen we should be able to calculate fee in Dynamic manner, in the way how it is done in solidity

## Implementation details

Generally impl. details could check in solidity impl. https://github.com/sygmaprotocol/sygma-solidity/pull/120/files#diff-1307091af2cb95ebc29d676cd09c6caa5390635ba11c8e4d461b07fb2abfd850

This handler should contain two main functions:
- collectFee https://github.com/sygmaprotocol/sygma-solidity/blob/master/contracts/handlers/fee/FeeHandlerWithOracle.sol#L114

- calculateFee https://github.com/sygmaprotocol/sygma-solidity/blob/master/contracts/handlers/fee/FeeHandlerWithOracle.sol#L132

Flow:
 - Deposit extrinsic should be updated with feeData []bytes param. 
- Then this params is used by FeeHandler to calculate fee and check the FeeOracle signature. 
- If signature is wrong ()does not belong to FeeOracle) then error returned
- if it is true, then calculated amount is sub from deposit amount

**Comment by MakMuftic** [comment]
I missed this issue when I was creating new issues for dynamic fee handling on the substrate - so it is replaced with #73
