### ISSUE TITLE
Add RPC endpoint for calculating inclusion fee

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-substrate-pallets#72]
This will facilitate Fee Oracle's ability to provide gas estimates for substrate chains.

## Implementation details

This endpoint should accept one argument, representing `length_fee` calculated based on concrete extrinsic.
Based on this parameter, the pallet should calculate the inclusion fee as [described in substrate documentation.](https://docs.substrate.io/build/tx-weights-fees/)

## Testing details

- [ ] Add unit tests

## Acceptance Criteria

- [ ] Sygma pallet exposes working endpoint for calculating inclusion fee
- [ ] Passing unit and e2e tests

**Comment by itsbobbyzzz168** [comment]
We have changed the implementation of dynamic fee. We will close these issues for now. Epic will exist for archive purposes.
