### ISSUE TITLE
Implement dynamic fee handler

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-substrate-pallets#73]
We need to add a handler for dynamic fee bridging requests.

## Implementation details

The first step is to update the Deposit extrinsic with `feeData` parameter (`[]bytes`). This parameter is then passed on to the fee handler.

Dynamic Fee handler should:
- validate fee oracle signature on fee estimate message (return error if the signature is not valid)
- based on context process fee estimate message to calculate final_fee (described below)
- charge fee

We need to process the fee estimate message differently based on context:

_this processing logic needs to be reused when implementing issue #74, so we should from start think how to make it reusable_

**Token transfer: fee is paid in a token being transferred**
_destination -> EVM_
`final_fee = feeOracleMsg.dstGasPrice * _gasUsed * feeOracleMsg.ter`

`_gasUsed` is the static amount of units of gas for this operation. On the EVM side, we can deploy multiple contracts to facilitate eventual different amounts for different resources. Initial implementation for the substrate can probably use just a hardcoded number for this, but we need to investigate whether is it possible to facilitate different values.

_destination -> Substrate_
`final_fee = feeOracleMsg.inclusionFee *  feeOracleMsg.ter`

**Generic messages: fee is paid in base currency**
_destination -> EVM_
`final_fee = feeOracleMsg.dstGasPrice * feeOracleMsg.msgGasLimit * feeOracleMsg.ber`

_destination -> Substrate_
`final_fee = feeOracleMsg.inclusionFee *  feeOracleMsg.ber`

## Testing details

- [ ] Add unit tests

## Acceptance Criteria

- [ ] Sygma pallet exposes working endpoint for calculating inclusion fee
- [ ] Passing unit and e2e tests

**Comment by freddyli7** [comment]
@MakMuftic quick question here, for the cases that the destination is substrate, does it mean something like both source and dest domain are substrate chain? for example, from Phala to Astar

**Comment by MakMuftic** [comment]
In theory, yes. I understand that nobody will use Sygma for bridging between Phala and Astar, as you mentioned (everybody can just use xcm), but my idea was to also define this case as there is a possibility of a substrate-based chain that is not part of Polkadot ecosystem.

**Comment by freddyli7** [comment]
ok, that makes sense to me, thanks for explanation

**Comment by freddyli7** [comment]
> In theory, yes. I understand that nobody will use Sygma for bridging between Phala and Astar, as you mentioned (everybody can just use xcm), but my idea was to also define this case as there is a possibility of a substrate-based chain that is not part of Polkadot ecosystem.

ok, that makes sense to me, thanks for explanation

**Comment by itsbobbyzzz168** [comment]
We have changed the implementation of dynamic fee. We will close these issues for now. Epic will exist for archive purposes.
