### ISSUE TITLE
Add RPC endpoint for calculating fee

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-substrate-pallets#74]
The user needs the ability for on-chain verifying fee estimates provided by Fee Oracle and calculating the final fee.

This endpoint should use the same logic used for calculating the final fee on executing the deposit. This provides the user a certainty that the final fee amount returned by this RPC endpoint will be the same as the amount that is going to be charged on deposit.

## Implementation details

The logic for calculating the final fee is described in issue #73

## Testing details

- [ ] Add unit tests

## Acceptance Criteria

- [ ] Sygma pallet exposes working endpoint for calculating inclusion fee
- [ ] Passing unit and e2e tests

**Comment by itsbobbyzzz168** [comment]
We have changed the implementation of dynamic fee. We will close these issues for now. Epic will exist for archive purposes.
