### ISSUE TITLE
Constant Weight Assigned to Linear-complexity Substrate Call

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-substrate-pallets#89]
The Substrate runtime call execute_proposal takes an arbitrary batch of proposals to execute. The size of this batch is not taken into account in the call's assigned weight.

Location:
Chainsafe_Sygma_Substrate_Pallets/src/lib.rs#L547

Impact:
Maliciously crafted transactions could cause excessive load, degrading network performance.

Remediation:
The number of proposals passed to the execute_proposal function should be factored into the call's weight calculation. Alternatively, the number of proposals per transaction could be limited, with a check performed before the function construct_ecdsa_signing_proposals_data is called.

**Comment by freddyli7** [comment]
The extrinsic weight is hardcoded as an annotation in the rust code currently regardless the number of proposals. it would require weight calculation to set it dynamically; however, we can definitely set a proposal number limit and also do pallet banchmark and provide a reasonable weight for now, we already have an issue for doing pallet banchmark #17

**Comment by tolak** [comment]
Yes, that was assigned to me, will do it as soon
