### ISSUE TITLE
Avoid pallet::without_storage_info in Production Code

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-substrate-pallets#94]
The Substrate attribute macro #[pallet::without_storage_info] is used on the bridge pallet. Since it allows blanket unbounded storage for all items in the pallet, it should never be used in a production environment.

Location
Chainsafe_Sygma_Substrate_Pallets/bridge/src/lib.rs#L61

Mitigation
The #[pallet::unbounded] attribute macro should be used instead on those (and only those) storage items that require unbounded size. See also https://docs.substrate.io/reference/frame-macros/.

**Comment by pesco** [comment]
Note that `without_storage_info` is also used on the `access-segregator`, `basic-fee-handler`, and `fee-handler-router` pallets, so this issue applies to them as well, even if they were not explicitly called out in the report.
